### ISSUE TITLE
Didn't find class "in.arjsna.lib.PassCodeView" on path: DexPathList

### ISSUE THREAD

**Issue by robertle2812** [Arjun-sna/android-passcodeview#2]
I use passcodeview with LolliPin in a project (passcodeview  is used as a view on lock screen and LolliPin for setting and changing pin code) and I receive this error (crash)
java.lang.ClassNotFoundException: Didn't find class "in.arjsna.lib.PassCodeView" on path: DexPathList[[zip file "/data/app/package_name.apk"],nativeLibraryDirectories=[/data/app-lib/package_name, /vendor/lib, /system/lib, /system/lib/arm]]

**Comment by Arjun-sna** [comment]
the log shows a wrong package name. if you have implemented the library from jcenter the package name should `in.arjsna.passcodeview.PassCodeView` . Please check your import.

**Comment by faheemkalsekar** [comment]
@Arjun-sna This is because [Usage](https://github.com/Arjun-sna/android-passcodeview#usage) says <in.arjsna.lib.PassCodeView>. Please update Usage guide.
