### ISSUE TITLE
Not working with Android 17

### ISSUE THREAD

**Issue by Anth06ny** [Arjun-sna/android-passcodeview#6]
Maybe it's me I m doing something wrong but it's working on my Android 24 but not with my Android 17.
On ly the first digit changing

**Comment by Arjun-sna** [comment]
Please provide more details on the issue.

**Comment by Kvazios** [comment]
On pre-lollipop devices only first circle filled with color, other stay empty

**Comment by Anth06ny** [comment]
Exact

**Comment by 2hamed** [comment]
I have the same problem. The backspace icon appears empty too.

**Comment by Arjun-sna** [comment]
fixed on latest release v1.2.1
