### ISSUE TITLE
Add "setEmptyDrawable" and "setFilledDrawable" methods

### ISSUE THREAD

**Issue by ocanhacom** [Arjun-sna/android-passcodeview#8]
First of all, congratulations for the awesome work! Really loved the library. I just want to ask if is it possible, when you have some time  to do it, of course, add these two methods, to edit programatically both empty and filled drawable direct on Java.

Looking forward for your response, and again, congrats!

**Comment by Arjun-sna** [comment]
added feature in latest release v1.2.1
